# Generated by Django 5.0.4 on 2024-04-10 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goal',
            old_name='goal_time_progress',
            new_name='excercise_goal',
        ),
        migrations.RenameField(
            model_name='goal',
            old_name='goal_time',
            new_name='meditation_goal',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='goal_name',
        ),
        migrations.AddField(
            model_name='goal',
            name='excercise_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='goal',
            name='meditation_time',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='goal',
            name='screen_goal',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='goal',
            name='screen_time',
            field=models.IntegerField(default=1),
        ),
    ]
