# Generated by Django 5.0.4 on 2024-04-10 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0002_rename_goal_time_progress_goal_excercise_goal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='excercise_goal',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='goal',
            name='meditation_goal',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='goal',
            name='screen_goal',
            field=models.FloatField(default=3),
        ),
    ]
