# Generated by Django 5.0.4 on 2024-04-10 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0004_alter_goal_meditation_time_alter_goal_screen_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='excercise_time',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='goal',
            name='meditation_goal',
            field=models.FloatField(default=10),
        ),
        migrations.AlterField(
            model_name='goal',
            name='meditation_time',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='goal',
            name='screen_time',
            field=models.FloatField(default=0),
        ),
    ]
