# Generated by Django 5.0.4 on 2024-04-11 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0005_alter_goal_excercise_time_alter_goal_meditation_goal_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mood',
        ),
    ]
