# Generated by Django 5.0.4 on 2024-04-11 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0006_delete_mood'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goal',
            old_name='user',
            new_name='user_id',
        ),
    ]
